<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>

<link rel="stylesheet" type="text/css" media="all" href="<?= $block->getViewFileUrl('Shatchi_Catalogue::css/wow_book.css') ?>" />
<link rel="stylesheet" type="text/css" media="all" href="<?= $block->getViewFileUrl('Shatchi_Catalogue::css/style.css') ?>" />
<link rel="stylesheet" type="text/css" media="all" href="<?= $block->getViewFileUrl('Shatchi_Catalogue::css/preview.css') ?>" />

<script src="<?= $block->getViewFileUrl('Shatchi_Catalogue::js/modernizr-1.6.min.js') ?>"></script>
