<?php

/** @var \Magento\Catalog\Block\Product\ListProduct $block */
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_imageHelper = $this->helper('Magento\Catalog\Helper\Image');
?>

<?php if ($_productCollection->getSize()): ?>
    <ol class="products list items product-items">
        <?php foreach ($_productCollection as $_product): ?>
            <?php
            $productUrl = $_product->getProductUrl();
            
            $productName = $_helper->productAttribute($_product, $_product->getName(), 'name');
            $dataName = htmlspecialchars($productName, ENT_QUOTES, 'UTF-8');

            $price = $_product->getFinalPrice();
            $isInStock = $_product->isAvailable() ? 'in' : 'out';
            $image = $_imageHelper->init($_product, 'category_page_grid')->resize(300, 300);
            $hoverImage = $_imageHelper->init($_product, 'category_page_grid-hover')->resize(300, 300);
            $color = $_product->getAttributeText('color');
            ?>
            <li class="item product product-item"
                data-price="<?= $price ?>"
                data-stock="<?= $isInStock ?>"
                data-position="<?= $_product->getCatIndexPosition() ?? 0 ?>"
                data-name="<?= $dataName ?>"> <!-- Add name attribute for sorting -->
                
                <div class="product-item-info type1" data-container="product-grid">
                    <div class="product photo product-item-photo">
                        <a href="<?= $productUrl ?>" tabindex="-1">
                            <?php
                            $productImage = $block->getImage($_product, 'category_page_grid');
                            $productImageUrl = $productImage->getImageUrl();
                            $productHoverImage = $block->getImage($_product, 'category_page_grid-hover');
                            $hoverImageUrl = $productHoverImage->getImageUrl();
                            ?>
                            <img class="product-image-photo default_image" src="<?= $productImageUrl ?>" width="300" height="300" alt="<?= $productName ?>" />

                            <img class="product-image-photo hover_image" src="<?= $hoverImageUrl ?>" width="300" height="300" alt="<?= $productName ?>" />
                        </a>
                    </div>

                    <div class="product details product-item-details">
                        <strong class="product name product-item-name">
                            <a class="product-item-link" href="<?= $productUrl ?>">
                                <?= $productName ?>
                            </a>
                        </strong>


                        <?php
                        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                        $context = $objectManager->get(\Magento\Framework\App\Http\Context::class);
                        $isLoggedIn = $context->getValue(\Magento\Customer\Model\Context::CONTEXT_AUTH);
                        ?>

                        <?php if (!$isLoggedIn): ?>
                            <div class="price-box price-final_price">
                                <span class="price-container price-final_price tax weee">
                                    <span class="price-wrapper ">£<span class="price starprice">**˙**H</span></span>
                                </span>
                            </div>

                            <div class="callforprice-action callforprice-action-<?= $_product->getId(); ?>" novalidate="novalidate">
                                <div class="price-box price-final_price"
                                    data-role="priceBox"
                                    data-product-id="<?= $_product->getId(); ?>"
                                    data-price-box="product-id-<?= $_product->getId(); ?>"
                                    style="display: none;">
                                </div>
                                <button type="button"
                                    title="<?php echo __('Login for price'); ?>"
                                    class="action tocart primary"
                                    id="product-callforprice-<?php echo $_product->getId(); ?>">
                                    <img class="mpcfp-icon"
                                        src="<?php echo $block->getViewFileUrl('Mageplaza_CallForPrice::img/icon_cfp_bt.png'); ?>"
                                        alt="">
                                    <span><?php echo __('Login for price'); ?></span>
                                </button>
                            </div>
                        <?php else: ?>
                            <div class="price-box price-final_price">
                            <span class="price-container price-final_price tax weee">
                                <span class="price-wrapper">£<span class="price"><?= number_format($price, 2) ?></span></span>
                            </span>
                        </div>

                        <?php endif; ?>



                        <div class="product-item-inner">
                            <div class="product actions product-item-actions">
                                <a href="#" class="action towishlist actions-secondary"
                                    title="<?= $block->escapeHtml(__('Add to Wish List')); ?>"
                                    aria-label="<?= $block->escapeHtml(__('Add to Wish List')); ?>"
                                    data-post='<?= $block->getAddToWishlistParams($_product); ?>'
                                    data-action="add-to-wishlist" role="button">
                                    <span><?= __('Add to Wish List') ?></span>
                                </a>

                                <div class="actions-primary">
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" action="<?= $postParams['action']; ?>" method="post">
                                            <input type="hidden" name="product" value="<?= $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?= \Magento\Framework\App\Action\Action::PARAM_NAME_URL_ENCODED; ?>"
                                                value="<?= $postParams['data'][\Magento\Framework\App\Action\Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit" title="<?= __('Add to Cart') ?>" class="action tocart primary">
                                                <span><?= __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <div class="stock unavailable"><span><?= __('Out of stock') ?></span></div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
    </ol>
<?php else: ?>
    <div class="message info empty">
        <div><?= __('No products found.') ?></div>
    </div>
<?php endif; ?>