<div style="background-color: #fbfbfb;padding: 4rem 0;">
   <div class="container">
      <div id="gifts-products" class="porto-products title-border-bottom col-sm-12 col-md-8 offset-sm-2" style="min-height: 50vh;">
         <div class="slider-wrapper">
            <div class="mygallery justified-gallery" data-lightbox="gallery">
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/0161-FRAME-GRADUATION-F60320.webp') ?>" data-fancybox="gallery">
                  <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/thumbs/0161-FRAME-GRADUATION-F60320.webp') ?>">
               </a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/11793-STEAM-SCOOTER-ANY-1.webp') ?>" data-fancybox="gallery">
                  <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/thumbs/11793-STEAM-SCOOTER-ANY-1.webp') ?>">
               </a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/15513-CANDLE-GLASS-LENTERN-SILVER.webp') ?>" data-fancybox="gallery">
                  <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/thumbs/15513-CANDLE-GLASS-LENTERN-SILVER.webp') ?>">
               </a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/63457B-FRAME-BELL-F63457B.webp') ?>" data-fancybox="gallery">
                  <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/thumbs/63457B-FRAME-BELL-F63457B.webp') ?>">
               </a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/117052-1.webp') ?>" data-fancybox="gallery">
                  <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/thumbs/117052-1.webp') ?>">
               </a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/117052-2.webp') ?>" data-fancybox="gallery">
                  <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/thumbs/117052-2.webp') ?>">
               </a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/117055.webp') ?>" data-fancybox="gallery">
                  <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/thumbs/117055.webp') ?>">
               </a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/117057-mix.webp') ?>" data-fancybox="gallery">
                  <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/thumbs/117057-mix.webp') ?>">
               </a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/117068-2.webp') ?>" data-fancybox="gallery">
                  <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/thumbs/117068-2.webp') ?>">
               </a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/117072-MIX.webp') ?>" data-fancybox="gallery">
                  <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/thumbs/117072-MIX.webp') ?>">
               </a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/118390.webp') ?>" data-fancybox="gallery">
                  <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/thumbs/118390.webp') ?>">
               </a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/142200.webp') ?>" data-fancybox="gallery">
                  <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/thumbs/142200.webp') ?>">
               </a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/212500.webp') ?>" data-fancybox="gallery">
                  <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/thumbs/212500.webp') ?>">
               </a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/BOX-KEEPSAKE.webp') ?>" data-fancybox="gallery">
                  <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/thumbs/BOX-KEEPSAKE.webp') ?>">
               </a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/ChariotsSpeedPipes-21.webp') ?>" data-fancybox="gallery">
                  <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/thumbs/ChariotsSpeedPipes-21.webp') ?>">
               </a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/chariots-pipes-13.webp') ?>" data-fancybox="gallery">
                  <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/thumbs/chariots-pipes-13.webp') ?>">
               </a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/MG_2412.webp') ?>" data-fancybox="gallery">
                  <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/thumbs/MG_2412.webp') ?>">
               </a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/mood-octopus-45.webp') ?>" data-fancybox="gallery">
                  <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/thumbs/mood-octopus-45.webp') ?>">
               </a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/Socks.webp') ?>" data-fancybox="gallery">
                  <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/thumbs/Socks.webp') ?>">
               </a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/Socks-Nana.webp') ?>" data-fancybox="gallery">
                  <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/thumbs/Socks-Nana.webp') ?>">
               </a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/SQ0006.webp') ?>" data-fancybox="gallery">
                  <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/gifts/thumbs/SQ0006.webp') ?>">
               </a>
            </div>
           
         </div>
         <div class="col-md-12 d-flex justify-content-center align-items-center flex-column">
            <div class="slider-wrapper">
               <h3 style="font-size: 3rem;" class="mt-5">Available Soon</h3>
            </div>
         </div>
      </div>
   </div>
</div>