<div style="background-color: #fbfbfb;padding: 4rem 0;">
   <div class="container">
      <div id="outdoor-products" class="porto-products title-border-bottom col-sm-12 col-md-8 offset-sm-2" style="min-height: 50vh;">
         <div class="slider-wrapper">
            <div class="mygallery justified-gallery" data-lightbox="gallery">
              <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/250006-2.3.webp') ?>" data-lightbox="gallery-item">
                <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/thumbs/250006-2.3.webp') ?>">
              </a>
              <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/250011-3.webp') ?>" data-lightbox="gallery-item">
                <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/thumbs/250011-3.webp') ?>">
              </a>
              <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/250017-2.webp') ?>" data-lightbox="gallery-item">
                <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/thumbs/250017-2.webp') ?>">
              </a>
              <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/250022-3.webp') ?>" data-lightbox="gallery-item">
                <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/thumbs/250022-3.webp') ?>">
              </a>
              <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/250023-30.webp') ?>" data-lightbox="gallery-item">
                <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/thumbs/250023-30.webp') ?>">
              </a>
              <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/250026-3.webp') ?>" data-lightbox="gallery-item">
                <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/thumbs/250026-3.webp') ?>">
              </a>
              <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/250028-15.webp') ?>" data-lightbox="gallery-item">
                <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/thumbs/250028-15.webp') ?>">
              </a>
              <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/250035-13.webp') ?>" data-lightbox="gallery-item">
                <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/thumbs/250035-13.webp') ?>">
              </a>
              <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/250035-14.webp') ?>" data-lightbox="gallery-item">
                <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/thumbs/250035-14.webp') ?>">
              </a>
              <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/250035-21.webp') ?>" data-lightbox="gallery-item">
                <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/thumbs/250035-21.webp') ?>">
              </a>
              <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/992300-2.webp') ?>" data-lightbox="gallery-item">
                <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/thumbs/992300-2.webp') ?>">
              </a>
              <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/992300-32.webp') ?>" data-lightbox="gallery-item">
                <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/thumbs/992300-32.webp') ?>">
              </a>
              <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/992600-10.webp') ?>" data-lightbox="gallery-item">
                <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/thumbs/992600-10.webp') ?>">
              </a>
              <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/992600-20-Lifestyle.webp') ?>" data-lightbox="gallery-item">
                <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/thumbs/992600-20-Lifestyle.webp') ?>">
              </a>
              <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/992700-6.webp') ?>" data-lightbox="gallery-item">
                <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/thumbs/992700-6.webp') ?>">
              </a>
              <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/992700-12.webp') ?>" data-lightbox="gallery-item">
                <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/thumbs/992700-12.webp') ?>">
              </a>
              <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/CQ1012.webp') ?>" data-lightbox="gallery-item">
                <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/thumbs/CQ1012.webp') ?>">
              </a>
              <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/CQ1012-1-BURGUNDY.webp') ?>" data-lightbox="gallery-item">
                <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/thumbs/CQ1012-1-BURGUNDY.webp') ?>">
              </a>
              <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/MG_0414.webp') ?>" data-lightbox="gallery-item">
                <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/thumbs/MG_0414.webp') ?>">
              </a>
              <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/SF-005-25.webp') ?>" data-lightbox="gallery-item">
                <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/thumbs/SF-005-25.webp') ?>">
              </a>
              <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/MSPA-Model-F-MO061-3.webp') ?>" data-lightbox="gallery-item">
                <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/thumbs/MSPA-Model-F-MO061-3.webp') ?>">
              </a>
              <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/MSPA-Model-F-TU061-1.webp') ?>" data-lightbox="gallery-item">
                <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/thumbs/MSPA-Model-F-TU061-1.webp') ?>">
              </a>
              <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/MSPA-Model-M-OT061-6.webp') ?>" data-lightbox="gallery-item">
                <img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/outdoor/thumbs/MSPA-Model-M-OT061-6.webp') ?>">
              </a>
            </div>
         </div>
         <div class="col-md-12 d-flex justify-content-center align-items-center flex-column">
            <div class="slider-wrapper">
               <h3 style="font-size: 3rem;" class="mt-5">Available Soon</h3>
            </div>
         </div>
      </div>
   </div>
</div>