<div style="background-color: #fbfbfb;padding: 4rem 0;">
   <div class="container">
      <div id="party-products" class="porto-products title-border-bottom col-sm-12 col-md-8 offset-sm-2" style="min-height: 50vh;">
         <div class="slider-wrapper">
            <div class="mygallery justified-gallery" data-lightbox="gallery">
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/21B-wide.webp') ?>" data-lightbox="gallery-item"><img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/thumbs/21B-wide.webp') ?>"></a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/60-blue-6-backdrop.webp') ?>" data-lightbox="gallery-item"><img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/thumbs/60-blue-6-backdrop.webp') ?>"></a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/70-multiv2.webp') ?>" data-lightbox="gallery-item"><img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/thumbs/70-multiv2.webp') ?>"></a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/1886-12.2-combined.webp') ?>" data-lightbox="gallery-item"><img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/thumbs/1886-12.2-combined.webp') ?>"></a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/7170-5.webp') ?>" data-lightbox="gallery-item"><img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/thumbs/7170-5.webp') ?>"></a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/7170-6.webp') ?>" data-lightbox="gallery-item"><img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/thumbs/7170-6.webp') ?>"></a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/10020-BALLOONS-BLACK-ORANGE-30PCS-100200.webp') ?>" data-lightbox="gallery-item"><img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/thumbs/10020-BALLOONS-BLACK-ORANGE-30PCS-100200.webp') ?>"></a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/11137-BALLOONS-STANDARD-PINK-200-PK-111370.webp') ?>" data-lightbox="gallery-item"><img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/thumbs/11137-BALLOONS-STANDARD-PINK-200-PK-111370.webp') ?>"></a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/11137-BALLOONS-STANDARD-PINK-200-PK-111370.webp') ?>" data-lightbox="gallery-item"><img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/thumbs/11137-BALLOONS-STANDARD-PINK-200-PK-111370.webp') ?>"></a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/11145-BALLOONS-LIGHT-GREEN-005PK-111450.webp') ?>" data-lightbox="gallery-item"><img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/thumbs/11145-BALLOONS-LIGHT-GREEN-005PK-111450.webp') ?>"></a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/11150-BALLOONS-LIGHT-BLUE-050PCS-111500.webp') ?>" data-lightbox="gallery-item"><img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/thumbs/11150-BALLOONS-LIGHT-BLUE-050PCS-111500.webp') ?>"></a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/11678-LIGHT-PINK-PULLBOW-30MM-20PK-116780.webp') ?>" data-lightbox="gallery-item"><img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/thumbs/11678-LIGHT-PINK-PULLBOW-30MM-20PK-116780.webp') ?>"></a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/20022-BALLOONS-POLKA-DOT-LIGHT-PINK-25PCS.webp') ?>" data-lightbox="gallery-item"><img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/thumbs/20022-BALLOONS-POLKA-DOT-LIGHT-PINK-25PCS.webp') ?>"></a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/21004-BALLOONS-FOIL-PINK.webp') ?>" data-lightbox="gallery-item"><img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/thumbs/21004-BALLOONS-FOIL-PINK.webp') ?>"></a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/21004-BALLOONS-FOIL-P-PINK.webp') ?>" data-lightbox="gallery-item"><img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/thumbs/21004-BALLOONS-FOIL-P-PINK.webp') ?>"></a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/21009-FOIL-BALLOON-5-SILVER.webp') ?>" data-lightbox="gallery-item"><img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/thumbs/21009-FOIL-BALLOON-5-SILVER.webp') ?>"></a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/111160.webp') ?>" data-lightbox="gallery-item"><img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/thumbs/111160.webp') ?>"></a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/112240.webp') ?>" data-lightbox="gallery-item"><img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/thumbs/112240.webp') ?>"></a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/112260.webp') ?>" data-lightbox="gallery-item"><img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/thumbs/112260.webp') ?>"></a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/115001.webp') ?>" data-lightbox="gallery-item"><img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/thumbs/115001.webp') ?>"></a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/118330.webp') ?>" data-lightbox="gallery-item"><img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/thumbs/118330.webp') ?>"></a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/125490.webp') ?>" data-lightbox="gallery-item"><img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/thumbs/125490.webp') ?>"></a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/140020.webp') ?>" data-lightbox="gallery-item"><img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/thumbs/140020.webp') ?>"></a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/140150.webp') ?>" data-lightbox="gallery-item"><img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/thumbs/140150.webp') ?>"></a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/140160-4.webp') ?>" data-lightbox="gallery-item"><img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/thumbs/140160-4.webp') ?>"></a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/140220.webp') ?>" data-lightbox="gallery-item"><img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/thumbs/140220.webp') ?>"></a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/140260.webp') ?>" data-lightbox="gallery-item"><img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/thumbs/140260.webp') ?>"></a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/140300.webp') ?>" data-lightbox="gallery-item"><img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/thumbs/140300.webp') ?>"></a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/300600.webp') ?>" data-lightbox="gallery-item"><img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/thumbs/300600.webp') ?>"></a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/6920145833001-6920145833018-1.webp') ?>" data-lightbox="gallery-item"><img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/thumbs/6920145833001-6920145833018-1.webp') ?>"></a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/6956702502479-11.webp') ?>" data-lightbox="gallery-item"><img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/thumbs/6956702502479-11.webp') ?>"></a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/Happy_Birthday-5.webp') ?>" data-lightbox="gallery-item"><img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/thumbs/Happy_Birthday-5.webp') ?>"></a>
               <a href="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/MG_2137.webp') ?>" data-lightbox="gallery-item"><img src="<?= $block->getViewFileUrl('Shatchi_ProductTab/images/party/thumbs/MG_2137.webp') ?>"></a>
            </div>
         </div>
         <div class="col-md-12 d-flex justify-content-center align-items-center flex-column">
            <div class="slider-wrapper">
               <h3 style="font-size: 3rem;" class="mt-5">Available Soon</h3>
            </div>
         </div>
      </div>
   </div>
</div>